stages:
  - build

build:
  stage: build
  script:
    - ls -ltra
    - ls ./ci
    - chmod +x ./ci/run_envoy_docker.sh
    - chmod +x ./ci/do_ci.sh
    - /bin/sh ./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.release'
