image: envoyproxy/envoy-build:latest

include:
  - project: 'davmey/pipelines'
    ref: master
    file: '/build_docker_nexus.yaml'

before_script:
    - echo "build --disk_cache=$CI_PROJECT_DIR/.cache" >> .bazelrc

cache:
  key: bazel_cache
  paths:
    - .cache/

variables:
  DEVOPS_CONTAINER_PATH: /identity-access/envoy
  DEVOPS_DOCKERFILE_PATH: deployment

stages:
  - build
  - publish

build:
  stage: build  
  script:
    - bazel build //source/exe:envoy-static
    - cp $CI_PROJECT_DIR/bazel-bin/source/exe/envoy-static $CI_PROJECT_DIR/deployment
    - ls -ltra $CI_PROJECT_DIR
  artifacts:
    expire_in: 1 week
    paths:
      - envoy-static
 
build_docker_nexus:
  stage: publish
  only:
    refs:
      - master

# trigger downstream build and redeploy 
#staging:
#  variables:
#    ENVIRONMENT: staging
#  stage: deploy
#  trigger: envoy-config
