image: envoyproxy/envoy-build:latest

include:
  - project: 'davmey/pipelines'
    ref: master
    file: '/build_docker_nexus.yaml'

variables:
  DEVOPS_CONTAINER_PATH: /identity-access/envoy
  DEVOPS_DOCKERFILE_PATH: deployment

stages:
  - build
  - publish

build:
  stage: build  
  script:
    - mkdir ../output
    - bazel --output_user_root=../output build //source/exe:envoy-static
    - ls bazel-bin/source/exe
    - tar cvfz build.tgz bazel-bin/source/exe
  artifacts:
    expire_in: 1 week
    paths:
      - ./build.tgz 
 
build_docker_nexus:
  stage: publish
  only:
    refs:
      - master

# trigger downstream build and redeploy 
#staging:
#  variables:
#    ENVIRONMENT: staging
#  stage: deploy
#  trigger: envoy-config
