image: envoyproxy/envoy-build:latest

stages:
  - build

build:
  stage: build  
  script:
    - bazel build //source/exe:envoy-static
    - tar cvfz envoy.tgz ./*
#    - apt-get update
#    - apt-get install docker-ce docker-ce-cli containerd.io
#    - docker run hello-world
#    - docker build -f ci/Dockerfile-envoy-image -t envoy .
  artifacts:
    expire_in: 1 week
    paths: 
     - ./envoy.tgz
 
