image: alpine:latest

stages:
  - build

build:
  stage: build  
  script:
    - chmod +x ./ci/run_envoy_docker.sh
    - chmod +x ./ci/do_ci.sh
    - bash ./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.release'
