image: envoyproxy/envoy-build:latest

stages:
  - build
  - publish

build:
  stage: build  
  script:
    - bazel build //source/exe:envoy-static

publish:
  stage: publish
  script:
    - docker build -f ci/Dockerfile-envoy-image -t envoy .

 
