image: envoyproxy/envoy-build:latest

before_script:
    - echo "build --disk_cache=$CI_PROJECT_DIR/.cache" >> .bazelrc

cache:
  key: bazel_cache
  paths:
    - .cache/

variables:
  DEVOPS_CONTAINER_PATH: /identity-access/envoy
  DEVOPS_DOCKERFILE_PATH: deployment

stages:
  - build
  - publish

build:
  tags: 
    - docker+machine
  stage: build  
  script:
    - bazel build //source/exe:docker-build
  
push_listener:
  stage: push
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - bazel run //soucre/exe:docker-push


# trigger downstream build and redeploy 
#staging:
#  variables:
#    ENVIRONMENT: staging
#  stage: deploy
#  trigger: envoy-config
