image: envoyproxy/envoy-build:latest

stages:
  - build

build:
  stage: build  
  script:
    - bazel build //source/exe:envoy-static
    - ls ./bazel-bin/source/exe
    - tar cvfz stuff.tgz bazel-bin/*
  artifacts:
    expire_in: 1 week
    paths:
      - ./bazel-bin/source/exe/*
      - ./stuff.tgz 
 
