image: envoyproxy/envoy-build:latest

stages:
  - build

build:
  stage: build  
  script:
    - bazel build //source/exe:envoy-static
    - which zip
    - sudo apt-get update
    - sudo apt-get install docker-ce docker-ce-cli containerd.io
    - sudo docker run hello-world
    - docker build -f ci/Dockerfile-envoy-image -t envoy .
  artifacts:
    expire_in: 1 week
    paths: 
     - bazel-bin/source/exe/envoy-static
 
